Server:
  port: 8081

spring:
  application:
    name: hr
  aop:
    proxy-target-class: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #MySQL????????MySQL8.0????????com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai #MySQL???URL
    username: root #MySQL??????
    password: root #MySQL????
    druid:
      validation-query: SELECT 1 FROM EMPLOYEE #???????SQL??
      initial-size: 10
      min-idle: 10
      max-active: 200
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      pool-prepared-statements: true
      max-open-prepared-statements: 100

mybatis-plus:
  type-aliases-package: com.hr.entity #??????entity???????????
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0

  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config:
    classpath: logback.xml
